"""add idempotency_key to translation_projects

Revision ID: 34e5bd614043
Revises: a8557707580e
Create Date: 2026-03-03 20:17:22.575452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e5bd614043'
down_revision: Union[str, Sequence[str], None] = 'a8557707580e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_projects', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_translation_projects_idempotency_key'), 'translation_projects', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_projects_idempotency_key'), table_name='translation_projects')
    op.drop_column('translation_projects', 'idempotency_key')
    # ### end Alembic commands ###
