"""add credit wallet uuid relation

Revision ID: 4f778f2bdc59
Revises: 7d4fb1844c08
Create Date: 2026-02-23 22:24:10.303470

"""
"""
 MIGRATION NAME MISMATCH WARNING

Revision ID: 4f778f2bdc59
Original name: add_credit_wallet_uuid_relation

ACTUAL CHANGE:
- This migration modifies translation_projects.status

NOTE:
The filename is misleading due to an earlier development change.
It has already been applied in environments and MUST NOT be renamed.

This note exists to prevent confusion during audits and debugging.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f778f2bdc59'
down_revision: Union[str, Sequence[str], None] = '7d4fb1844c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation_projects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation_projects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
