"""add output_file column to translation_projects

Revision ID: 67cdf998ac83
Revises: 0be2305d24ad
Create Date: 2026-03-01 22:03:01.584317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cdf998ac83'
down_revision: Union[str, Sequence[str], None] = '0be2305d24ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_projects', sa.Column('output_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_projects', 'output_file')
    # ### end Alembic commands ###
