"""add retry logic fields to translation_projects

Revision ID: 6e529129d058
Revises: 34e5bd614043
Create Date: 2026-03-03 20:35:38.009474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e529129d058'
down_revision: Union[str, Sequence[str], None] = '34e5bd614043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'translation_projects',
        sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'translation_projects',
        sa.Column('last_heartbeat', sa.DateTime(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_projects', 'last_heartbeat')
    op.drop_column('translation_projects', 'retry_count')
    # ### end Alembic commands ###
