"""add certification file to users

Revision ID: 957adc0f8c39
Revises: 8f3c1d2e7abc
Create Date: 2026-02-27 21:00:18.457751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '957adc0f8c39'
down_revision: Union[str, Sequence[str], None] = '8f3c1d2e7abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_events')
    op.drop_column('credit_wallets', 'monthly_allowance')
    op.alter_column('translation_projects', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='project_status_enum'),
               nullable=False)
    op.add_column('users', sa.Column('certification_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'certification_file')
    op.alter_column('translation_projects', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='project_status_enum'),
               nullable=True)
    op.add_column('credit_wallets', sa.Column('monthly_allowance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('stripe_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stripe_events_pkey'))
    )
    # ### end Alembic commands ###
