"""add created_at to credit_transactions

Revision ID: a8557707580e
Revises: 05528b6ac2da
Create Date: 2026-03-01 22:44:17.199550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8557707580e'
down_revision: Union[str, Sequence[str], None] = '05528b6ac2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transactions', 'created_at')
    # ### end Alembic commands ###
